docker_version: "24.0.5"
web_app_repo: "https://github.com/Infratify/lab-final-project.git"
web_app_image: "devops-bootcamp/final-project-faridamirul:latest"
monitoring_tools:
  - prometheus
  - grafana
grafana_admin_user: "admin"
grafana_admin_password: "StrongPassword123!"


