- hosts: monitoring
  become: yes
  tasks:
    - name: Include common setup
      import_playbook: common.yml

    - name: Deploy Prometheus
      import_role:
        name: prometheus

    - name: Deploy Grafana
      import_role:
        name: grafana
