name: Build, Push Docker Image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout main repo (needed for OIDC)
      - name: Checkout main repo
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials using OIDC
      - name: Configure AWS credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::938674806440:role/github
          aws-region: ap-southeast-1

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Clone lab-final-project repo
      - name: Clone lab-final-project
        run: |
          git clone https://github.com/Infratify/lab-final-project.git
          ls -lah lab-final-project

      # 5️⃣ Build Docker image from cloned repo
      - name: Build Docker image
        run: |
          IMAGE_NAME=devops-bootcamp/final-project-faridamirul
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./lab-final-project

      # 6️⃣ Tag Docker image for ECR
      - name: Tag Docker image for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_NAME=devops-bootcamp/final-project-faridamirul
          IMAGE_TAG=${GITHUB_SHA::8}
          ECR_URI=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_NAME
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      # 7️⃣ Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker push $ECR_URI:$IMAGE_TAG

      # 8️⃣ Set up Python and install dependencies
      - name: Set up Ansible + boto3
        run: |
            python3 -m pip install --upgrade pip
            pip install boto3 botocore ansible
            ansible-galaxy collection install amazon.aws


      # 9️⃣ Deploy via Ansible using SSM
      - name: Deploy via Ansible using SSM
        run: |
            ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
            -e "ci_image_tag=${GITHUB_SHA::8}" \
            -e "ansible_connection=amazon.aws.aws_ssm" \
            -e "ansible_user=ssm-user" \
            -e "ansible_region=ap-southeast-1"
        env:
            AWS_DEFAULT_REGION: ap-southeast-1
            AWS_REGION: ap-southeast-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}



    

    