name: Build, Push Docker Image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout main repo (needed for OIDC)
      - name: Checkout main repo
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials using OIDC
      - name: Configure AWS credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::938674806440:role/github
          aws-region: ap-southeast-1

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Clone lab-final-project repo
      - name: Clone lab-final-project
        run: |
          git clone https://github.com/Infratify/lab-final-project.git
          ls -lah lab-final-project

      # 5️⃣ Build Docker image from cloned repo
      - name: Build Docker image
        run: |
          IMAGE_NAME=devops-bootcamp/final-project-faridamirul
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./lab-final-project

      # 6️⃣ Tag Docker image for ECR
      - name: Tag Docker image for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_NAME=devops-bootcamp/final-project-faridamirul
          IMAGE_TAG=${GITHUB_SHA::8}
          ECR_URI=$ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_NAME
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      # 7️⃣ Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker push $ECR_URI:$IMAGE_TAG

     # 8️⃣ Deploy to Web Server via Ansible
      - name: Deploy to Web Server via Ansible
        run: |
            ansible-playbook -i inventory.ini playbook.yml -K \
            -e "ci_image_tag=${GITHUB_SHA::8}"
    

    